Rails.application.routes.draw do
  get 'purchases/index'
  get 'purchases/show'
  get 'purchases/new'
  get 'purchases/create'
  get 'purchases/update'
  get 'purchases/edit'
  get 'purchases/destroy'
  get 'opinions/index'
  get 'opinions/show'
  get 'opinions/new'
  get 'opinions/create'
  get 'opinions/update'
  get 'opinions/edit'
  get 'opinions/destroy'
  get 'opiniions/index'
  get 'opiniions/show'
  get 'opiniions/new'
  get 'opiniions/create'
  get 'opiniions/update'
  get 'opiniions/edit'
  get 'opiniions/destroy'
  get 'favorites/index'
  get 'favorites/show'
  get 'favorites/new'
  get 'favorites/create'
  get 'favorites/update'
  get 'favorites/edit'
  get 'favorites/destroy'
  get 'experiences/index'
  get 'experiences/show'
  get 'experiences/new'
  get 'experiences/create'
  get 'experiences/update'
  get 'experiences/edit'
  get 'experiences/destroy'
  get 'stores/index'
  get 'stores/show'
  get 'stores/new'
  get 'stores/create'
  get 'stores/update'
  get 'stores/edit'
  get 'stores/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/update'
  get 'users/edit'
  get 'users/destroy'
  get 'states/index'
  get 'states/show'
  get 'states/new'
  get 'states/create'
  get 'states/update'
  get 'states/edit'
  get 'states/destroy'
  get 'countries/index'
  get 'countries/show'
  get 'countries/new'
  get 'countries/create'
  get 'countries/update'
  get 'countries/edit'
  get 'countries/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end
